name: CI/CD Pipeline

on:
  push:
    branches: [main]

jobs:

  build-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18
      - run: npm install
      - run: npm test

  docker-build:
    needs: build-test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: docker build -t todo-app:${GITHUB_SHA::7} .
      - uses: aquasecurity/trivy-action@master
        with:
          image-ref: todo-app:${{ github.sha }}
          exit-code: '0'

  push-ecr:
    needs: docker-build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}
      - run: |
          aws ecr get-login-password \
          | docker login --username AWS --password-stdin ${{ secrets.ECR_URI }}
      - run: |
          docker build -t ${{ secrets.ECR_URI }}:${GITHUB_SHA::7} .
          docker push ${{ secrets.ECR_URI }}:${GITHUB_SHA::7}
